[staging]
staging-host ansible_host=178.104.51.228 ansible_user=forge

[prod]
prod-host ansible_host=51.75.18.212 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
